### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by moghaddam** [PartnerCenterSamples/Partner-Center-Java-SDK#10]
Hi Guys

I'm really interested to know if there is any plan to update this SDK based on latest changes on Partner Center REST API or do any minor bug fixes and improvements. Based on the state of issues and the only open pull request that has not been even reviewed after 7 month, it looks like that this is a sort of abandoned project. 
I was thinking about doing some improvements in this SDK (on behalf of my company) but it's not clear if our pull requests would be merged at all. Of course we can fork it and start developing our own branch, but the changes/improvements we need, can easily be implemented in a more general way so that it could be used by others (and vice versa).

@tameemansari Your input is appreciated

Regards
Ehsan

**Comment by tameemansari** [comment]
Let me check and follow up. can you drop me an email tansar at Microsoft. Thanks.

**Comment by epinter** [comment]
@tameemansari Any news ?

**Comment by tameemansari** [comment]
@isaiahwilliams has offered to help the broader community and has recently updated the codebase to bring it to parity with the .net sdk.
