### ISSUE TITLE
Unrecognized field "hasPurchasableAddons"

### ISSUE THREAD

**Issue by GustavoLlorente** [PartnerCenterSamples/Partner-Center-Java-SDK#11]
Hello,
I'm trying this library and I'm getting errors related to unknown attributes on several POJOS. The problem is these pojos don't have neither "@JsonIgnoreProperties(ignoreUnknown = true) annotation" nor other way to ignore this errors.

Is this library deprecated?

**Comment by ghost** [comment]
Hi @GustavoLlorente this issue has been addressed with the latest update. Please let us know if you have any other issues.
