### ISSUE TITLE
Samples for GetOfferDetail get incorrect response

### ISSUE THREAD

**Issue by Ruodong** [PartnerCenterSamples/Partner-Center-Java-SDK#13]
in https://github.com/PartnerCenterSamples/Partner-Center-Java-SDK/blob/master/Samples/src/main/java/com/microsoft/store/partnercenter/samples/offers/GetOfferDetails.java
line 44
Offer offer = partnerOperations.getOffers().byCountry( countryCode ).byId( "**8AA7E78B-B265-4AC6-ADA0-14900A8A3F94**" ).get();
a constant value **8AA7E78B-B265-4AC6-ADA0-14900A8A3F94** be used as a parameter for getOffers().byId(), need declare a private variables offerId get input as the parameter for getOffers().byId()

i write code as below,it's work well
String countryCode =
         this.getContext().getConsoleHelper().readNonEmptyString( "Enter the 2 digit country code to get its supported offers",
                                                                  "The country code can't be empty" );
     String offerId =  	this.getContext().getConsoleHelper().readNonEmptyString("Enter offerId to get its supported offer detail",
             "The offerId can't be empty" );
     
     this.getContext().getConsoleHelper().startProgress( MessageFormat.format( "Getting offers for {0}",
                                                                               countryCode ) );
     Offer offer = partnerOperations.getOffers().byCountry( countryCode ).byId(offerId).get();
     
pls help to fix it!

**Comment by ghost** [comment]
Hi @Ruodong, this issue has been resolved with the latest update. Please let us know if you have any other issues.
