### ISSUE TITLE
Model Offer missing attributes   SupportedBillingCycle

### ISSUE THREAD

**Issue by Ruodong** [PartnerCenterSamples/Partner-Center-Java-SDK#14]
In com.microsoft.store.partnercener.models.offers.Offer.java file
missing attributes SupportedBillingCycle, need below code 
I test it works
    /** 
     * Gets or sets the SupportedBillingCycles
     */
    
    private List<String> _SupportedBillingCycles;
    
    public List<String> getSupportedBillingCycles()
    {
    	return _SupportedBillingCycles;
    }
    
    public void setSupportedBillingCycles(List<String> value)
    {
    	_SupportedBillingCycles = value;
    }

**Comment by ghost** [comment]
Hi @Ruodong, this issue has been addressed with the latest update. Please let us know if you have any other issues.
