### ISSUE TITLE
NullPointer in BasePartnerCredentials

### ISSUE THREAD

**Issue by jordaniac89** [PartnerCenterSamples/Partner-Center-Java-SDK#24]
# Steps to reproduce

> Create PartnerCredentials with getInstance().generateByApplicationCredentials
> Call credentials.getExpiresAt()

## Expected behavior

> Retrieve expiresAt()

## Actual behavior

>java.lang.NullPointerException at com.microsoft.store.partnercenter.extensions.BasePartnerCredentials.getExpiresAt(BasePartnerCredentials.java:57)

## Diagnostic logs

> The problem is that jwtToken in BasePartnerCredentials is private and is never initialized or set anywhere.

## Environment

> Please share additional details about your environment.
> Version

**Comment by ghost** [comment]
Hi @jordaniac89, 

Thank you for bring this issue to my attention. I am in the process of migrating this repository to the Microsoft organization, and I will correct this issue as part of the migration. If you need a resolution now then the function should look like 
```java
@Override
public DateTime getExpiresAt()
{
    return this.getAADToken().getExpiryTime();
}
```

**Comment by ghost** [comment]
Hi @jordaniac89, you can find the repository for this project at https://github.com/Microsoft/Partner-Center-Java/. I am going to close this issue, but if you are still having issues or you find another bug please open a new issue using the issue tracker for the new repository.
