### ISSUE TITLE
[Help] Can not get the invoice line item when "totalCount" is odd number

### ISSUE THREAD

**Issue by chrislee1987** [PartnerCenterSamples/Partner-Center-Java-SDK#3]
If "totalCount" is odd , for example ,

{"totalCount":15,"items":[{"detailLineItemId":1,"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}

then

com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.store.partnercenter.models.ResourceCollection["items"]->java.util.ArrayList[7])

this exception will be throwed.

Can you tell me the reason of that, thank you very much.

**Comment by tameemansari** [comment]
closing the old item.
