### ISSUE TITLE
Wrong encoding in JSON in Request

### ISSUE THREAD

**Issue by mortenrummelhoff** [PartnerCenterSamples/Partner-Center-Java-SDK#7]
Looking when a Request is send it seems that when constructing the StringEntity in the PartnerServiceProxy.java class no Charset is specified. This leads to the String is being encoded with "ISO_8859_1". I believe correct encoding should be "UTF-8" as this is the standard for JSON.

**Comment by mortenrummelhoff** [comment]
#8

**Comment by birkestroem** [comment]
I agree with @mortenrummelhoff that it should follow the rfc [https://tools.ietf.org/html/rfc7159#section-8.1](https://tools.ietf.org/html/rfc7159#section-8.1).
But some people might depend on the faulty implementation by now. 

Is it possible to set the content-type header in the SDK? The receiving side will hopefully pick up on that.

I think your PR should set the content-type header to "application/json; charset=utf-8" if possible.

**Comment by ghost** [comment]
Hi @mortenrummelhoff the latest has incorporate a fix for this issue. Please let me know if you have any issues.
